[phases.setup]
# Install Python 3.11 and pip from Nix
nixPkgs = ["python311", "python311Packages.pip"]
nixPkgsExclude = ["mysql"]

[phases.install]
# Install dependencies from backend/requirements.txt
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt"
]

[phases.start]
# Start your FastAPI backend
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
